### ISSUE TITLE
User location shows up as "Unknown, Unknown" on clevertap dashboard

### ISSUE THREAD

**Issue by mohsinulhaq** [CleverTap/clevertap-react-native#107]
![image](https://user-images.githubusercontent.com/7688231/90805060-bd30ff00-e338-11ea-84b0-21390dfe0b0b.png)

As you can see, the latitude and longitude are correctly populating as a result of calling `setLocation` function. But how do we set the Location? Can't find anything in the docs.

**Comment by darshanclevertap** [comment]
@mohsinulhaq The city-level location is captured from the requests which hit our back end servers. If you can't see the city-level location, I suggest you raise a support ticket from the dashboard itself and it will notify the correct team which can fix this for you.

**Comment by darshanclevertap** [comment]
@mohsinulhaq Ensure that you're calling our `enableDeviceNetworkInfoReporting` method. This notifies our systems to track the requests to get city-level information as per GDPR laws. You can find the [method here](https://github.com/CleverTap/clevertap-react-native/blob/master/index.js#L206).

If the problem persists after using the above method, I would suggest raising a support ticket from the dashboard so that the concerned team can help you resolve the issue at the earliest.
Thanks!

**Comment by mohsinulhaq** [comment]
@darshanclevertap thanks, so do we have to enable only if we don't have our apps distributed outside the EU? Or does it store the location in compliance with GPDR?

**Comment by darshanclevertap** [comment]
@mohsinulhaq If GDPR laws apply to your app, then you should ask the user's consent before setting this method to `true`. By default, CleverTap doesn't track the location of a user from the SDK requests.

**Comment by mohsinulhaq** [comment]
ok, got it, thanks a lot! @darshanclevertap
