### ISSUE TITLE
HOW TO SETUP PUSH-NOTIFICATION IS NOT THERE IN DOCS FOR IOS

### ISSUE THREAD

**Issue by yoginair** [CleverTap/clevertap-react-native#15]

**Comment by Aditi3** [comment]
Hey @yoginair , 

To implement push notifications in iOS React Native,  please check included ExampleProject.js [(https://github.com/CleverTap/clevertap-react-native/blob/master/ExampleProject/ExampleProject.js)] 

Here you can see, by calling the below method: 

` // for iOS only: register for push notifications
        CleverTap.registerForPush();`

you can enable support for push notifications.

**Comment by VarshaJadhav** [comment]
@Aditi3 I also tried to adding `CleverTap.registerForPush();` in my root file, but again its not enabling push notification in Clevertap dashboard.

**Comment by Aditi3** [comment]
Thanks, @VarshaJadhav  for writing in.

I am sure that there must be some integration error at your end. Could you please write to support@clevertap.com - we will take a look at it?

**Comment by VarshaJadhav** [comment]
Hey @yogi Please check all the configuration required for iOS push notification are given in doc: https://github.com/CleverTap/clevertap-react-native/blob/HEAD/docs/install.md#manual-linking 

Once you successfully configured and integrated clevertap-react-native, Check in your xcode debugger for **APNs device token**

Because in my case instead of APNs device token FCM token was getting generated and hence iOS push notification was not getting enabled in Clevertap Dashboard.

**Comment by yoginair** [comment]
@VarshaJadhav thanks for the help 🥇 . @Aditi3 thanks

**Comment by AbhishekCode** [comment]
thanks

**Comment by HyuArzani** [comment]
Hello @VarshaJadhav is it not possible to integrate clevertap APN device token with firebase? because in my case i need firebase as provider to
