### ISSUE TITLE
In RN 0.65 Clevertap integration fails iOS builds by following documentation

### ISSUE THREAD

**Issue by shrmaky** [CleverTap/clevertap-react-native#187]
To fix this, i am not sure whether this is right implementation or not but made these changes -

In Podfile -

pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native', modular_headers: true
pod 'CleverTap-iOS-SDK', modular_headers: true

In AppDelegate.m, changed to -
```
#import <CleverTap-iOS-SDK/CleverTap.h>
#import <clevertap-react-native/CleverTapReactManager.h>
```

I am able to build now.

Can clevertap team work on a solution here?

**Comment by Aditi3** [comment]
@shrmaky Could you please check our [Troubleshooting Documentation ](https://github.com/CleverTap/clevertap-react-native/blob/master/docs/install.md#troubleshooting) under that, we have explained installation and integration using  `use_modular_headers!` 

Also need to use @import CleverTapSDK; instead of #import <CleverTapSDK/CleverTap.h> and @import CleverTapReact; instead of #import <CleverTapReact/CleverTapReactManager.h> in the AppDelegate class in case if using use_modular_headers! in the podfile.

**Comment by Aditi3** [comment]
Closing this thread, feel free to reopen if you need further help.
