### ISSUE TITLE
custom key-value from push notification 

### ISSUE THREAD

**Issue by shamshad17** [CleverTap/clevertap-react-native#208]
How can I get **key value pairs** from push notification in react native. I couldn't  find any way get this. Please help.

**Comment by darshanclevertap** [comment]
Hi @shamshad17 You need to add the CleverTap listeners as shown in the [Example here](https://github.com/CleverTap/clevertap-react-native/blob/52f0de2e49ccc15aea99e400f118d2a93da6a03e/Example/App.js#L1005)

If you have already tried this and are still facing an issue, please share a sample code with us so that we can help you debug.

**Comment by shamshad17** [comment]
Works Thanks. 

It gives type script error `Property 'CleverTapPushNotificationClicked' does not exist on type 'typeof import("~../node_modules/clevertap-react-native/index")`. You can add ts documentation for this also, it will be helpful for others.

**Comment by piyush-kukadiya** [comment]
@shamshad17 Thanks for reporting this. We will add it.

**Comment by shamshad17** [comment]
@darshanclevertap Unable to get data from push notification in android while app in not running. If app is in background its works fine. This is happing in android only. iOS works fine.

**Comment by MuckT** [comment]
Seeing the same thing here: https://github.com/valora-inc/wallet/issues/2087 .

I've updated to the most recent version of [clevertap-react-native 0.8.0](https://www.npmjs.com/package/clevertap-react-native), but I am still seeing this issue.

Code for adding our listeners is below; This is working on IOS, but not Android.
```JavaScript
    CleverTap.addListener('CleverTapPushNotificationClicked', async (event: any) => {
      const url = Platform.OS === 'ios' ? event.customExtras['wzrk_dl'] : event['wzrk_dl']
      if (url) {
        await this.handleOpenURL({ url }, true)
      }
    })
```

**Comment by MuckT** [comment]
@piyush-kukadiya yes that is exactly what I am seeing. One strange behavior is on Android when the app is closed using `getInitialUrl` appears to be working fine on Android 12.

```JavaScript
CleverTap.getInitialUrl(async (err: any, url) => {
  if (err) {
    // Handle the error here
  } else if (url) {
    await this.handleOpenURL({ url }, true)
  }
})

```

**Comment by piyush-kukadiya** [comment]
@MuckT Can you check once Is this happening when deeplink redirects user to a screen which is already visible. 
For example user is interacting with Launcher Screen and notification comes and click redirects to the same Launcher Activity. (This scenario is not handled by us since we provide click callback and deeplink redirection in oncreate() of lifecycle callback where as above scenario is meant for onResume())

**Comment by piyush-kukadiya** [comment]
@MuckT We have got support ticket from you. To avoid confusion and maintain only one thread I am closing this issue.
