### ISSUE TITLE
react native clevertap issue.

### ISSUE THREAD

**Issue by anil15051992** [CleverTap/clevertap-react-native#3]
Hi 
I am using clevertap- react-native npm in my ios react native project but it is throwing the following error 
" ld: framework not found CleverTapSDK
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

And also i am getting error while running the "pod 'CleverTap-iOS-SDK'" command on terminal.
and the error is as below
"[!] Unknown command: `CleverTap-iOS-SDK`
Did you mean: clean?"

So please some one help me with the solution for it.

Thanks in advance.

**Comment by pwilkniss** [comment]
@anil15051992   here's a link to instruction on how to use CocoaPods to install the sdk.   https://github.com/CleverTap/clevertap-react-native/blob/master/docs/install.md#ios

Basically create a Podfile.  Add `pod CleverTap-iOS-SDK` to it.  run pod install.  there is an example Podfile at the link above.

I am going to close this issue here.  If you have additional issues please feel free to email support at clevertap.com.
