### ISSUE TITLE
Android only receive push with RenderMax Enabled! 

### ISSUE THREAD

**Issue by ebellumat** [CleverTap/clevertap-react-native#304]
I spend an entire day implementing Clevertap React Native and on iOS, the Push Notifications worked just fine, on Android I only received a notification when I enabled the RenderMax flag on the user profile to receive a notification. 

What happened on the platform to show me that the notification was successfully sent but the user does not receive a notification at all? 

RenderMax is now mandatory to receive a simple push? 

I implemented the notification channels to make the test, and only worked with  RenderMax Enabled!

**Comment by darshanclevertap** [comment]
@ebellumat RenderMax is NOT mandatory to receive a normal push. A normal integration should allow receiving of push notifications.

Can you help us with a few answers so that we can help you better?

1. What is the version of the CleverTap React Native SDK being used by your app?
2. In Android, for rendering push notifications, are you using Invertase or using CleverTap's `FcmMessageListenerService` in the `AndroidManifest.xml` file or are you rendering the push notifications on your own?
3. Can you share the Make and Model of the devices you tested your Android push notifications on?

**Comment by darshanclevertap** [comment]
@ebellumat I see two Firebase Messaging Services. One is CleverTap's - `FcmMessageListenerService` and the other is `.MainNotificationService`

It is recommended that only one be used as it could cause race conditions when the push payload reaches the device.

Could you explain why are 2 services being used?

**Comment by ebellumat** [comment]
I will test. Thank you for the tip.
