### ISSUE TITLE
Why index.d.ts not maintained?

### ISSUE THREAD

**Issue by jdarshan5** [CleverTap/clevertap-react-native#365]
I am exploring clevertap from around a week, and I found that the documentation is not well maintained, like this one https://github.com/CleverTap/clevertap-react-native/blob/7c7af62bbf39f829ba428311906ded5355c72a3a/index.d.ts#L335-L340
you can see that values param is described as "array of strings", but still given "any" type in argument. Is there any reason to do so?

https://github.com/CleverTap/clevertap-react-native/blob/7c7af62bbf39f829ba428311906ded5355c72a3a/index.d.ts#L186-L190
Also in above code, we can not identify what exact keys are there to pass in.

**Comment by shivamsharma2710** [comment]
Hi @jdarshan5 

Please refer the developer documentation instead of `index.d.ts` to understand the complete usage of the following methods:

- [Push Primer doc](https://developer.clevertap.com/docs/react-native-push-notification#push-notifications-permission)
- [Set Multi Values For Key](https://developer.clevertap.com/docs/user-profiles-react-native#set-multi-values-for-key)

Closing this ticket for now. Feel free to reopen if you have any further queries related to the same.
