### ISSUE TITLE
iOS manual linking error: Could not find auto-linked framework 'CleverTapSDK'

### ISSUE THREAD

**Issue by ianrajs** [CleverTap/clevertap-react-native#42]
Hi, I'm trying to instal clevertap by manual linking.
and i got this error: 

> warning: Could not find auto-linked framework 'CleverTapSDK'
> Undefined symbols for architecture x86_64:
>   "_OBJC_CLASS_$_CleverTap", referenced from:
>       objc-class-ref in libCleverTapReact.a(CleverTapReactManager.o)
>       objc-class-ref in libCleverTapReact.a(CleverTapReact.o)
>      (maybe you meant: _OBJC_CLASS_$_CleverTapReactEventEmitter, _OBJC_CLASS_$_CleverTapReact , _OBJC_CLASS_$_CleverTapReactManager )
>   "_OBJC_CLASS_$_CleverTapInboxStyleConfig", referenced from:
>       objc-class-ref in libCleverTapReact.a(CleverTapReact.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ebellumat** [comment]
I have created my own fork of this dependency for this problem, i replace all imports starts with 'CleverTap SDK' to 'CleverTap-iOS-SDK', for example:

``` #import <CleverTapSDK/CleverTap.h>``` to 
``` #import <CleverTap-iOS-SDK/CleverTap.h>```

Use my fork if you don't want to have much work, i hope this helps.

**Comment by ebellumat** [comment]
For import of CleverTapReact i use #import <clevertap-react-native/CleverTapReactManager.h>

**Comment by Aditi3** [comment]
Hey @ebellumat 

Glad to know it worked for you for replacing the **#import** statements.

However, I would recommend try including the **use_frameworks!** in your podfile to avoid replacing the **#import** statements.

CleverTapSDK is a dynamic framework, by specifying use_frameworks! you can make CocoaPods integrate to your project via frameworks instead of static libraries. Therefore I suggest try including use_frameworks! in the pod file and then build your project.

I hope this will help.

**Comment by ebellumat** [comment]
**use_frameworks!** broke my entire project, for example:

```[!] The 'Pods-V1' target has transitive dependencies that include statically linked binaries: (/Users/erasmolbj/Documents/Git/app-clientereact/ios/Pods/GoogleMaps/Base/Frameworks/GoogleMapsBase.framework, /Users/erasmolbj/Documents/Git/app-clientereact/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework, /Users/erasmolbj/Documents/Git/app-clientereact/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMapsCore.framework, and /Users/erasmolbj/Documents/Git/app-clientereact/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework)```

**Comment by Aditi3** [comment]
Hi @ianrajs 

Seems like installation issue. Could you please verify the installation steps once at your end?

Ensure that you are including **libCleverTapReact.a** under Link Binary with Libraries.

Also, I recommend you to check out our Demo Application to verify the installation.
Helping Link: https://github.com/CleverTap/clevertap-react-native/tree/master/Starter

Thanks

**Comment by ianrajs** [comment]
Hi @Aditi3 
like @ebellumat, my entire project broke if I add **use_framework**! to my podfile.
So I decided to linked the clevertap manually. I have do this step:

- adding CleverTapReact.xcodeproj into the Libraries folder
- adding **libCleverTapReact.a** into **Link Binary with Libraries**.
- adding $(SRCROOT)/../node_modules/clevertap-react-native/ios in Header Search Path
- adding the account id and account token into info.plist

and then i got the error, even before I import CleverTapSDK in my project.

**Comment by ianrajs** [comment]
Hi @Aditi3 
I have trying to integrate clevertab into sample github https://github.com/CleverTap/clevertap-react-native/tree/master/Starter.
It is working if I install using podspec, but if trying linked manully. I got the same error with my project.
Any idea?

**Comment by Aditi3** [comment]
Hey @ianrajs 

Could you please verify you have added `pod 'CleverTap-iOS-SDK'` as a dependency in your iOS podfile? 

In the case of manual installation also, it is required to add CleverTapSDK as a dependency.

Try adding `pod 'CleverTap-iOS-SDK'` in your podfile. If your project configuration doesn't allow you to include **use_frameworks!**  in your podfile. I suggest installing CleverTapSDK as a static library instead of a dynamic framework that means without including **use_frameworks!**

Also, in that scenario you need to **#import <CleverTap-iOS-SDK/CleverTap.h>** instead of **<CleverTapSDK/CleverTap.h>** in your AppDelegate file.

Hope this helps.

**Comment by ianrajs** [comment]
Thanks @Aditi3,
My bad, I didn't adding pod 'CleverTap-iOS-SDK' in my podfile.

btw, how to #import <CleverTap-iOS-SDK/CleverTapReactManager.h>?
I have  trying use #import <clevertap-react-native/CleverTapReactManager.h> like @ebellumat suggestion. But its not working also.

**Comment by Aditi3** [comment]
@ianrajs  It is not required to make any modification for importing CleverTapReactManager header.

Simply use the **#import <CleverTapReact/CleverTapReactManager.h>**  statement as stated in our [documentation](https://github.com/CleverTap/clevertap-react-native/blob/master/docs/integration.md#ios).
